### PR TITLE
introduce template for regular meet up issues

### PR DESCRIPTION
**Pull request by OleMchls**
Any thoughts? Did I miss something?

I used it for the March edition and felt quite comfortable to have this at hand. This should also help future organisers to jump into organising a monthly edition.

@lydG

TODO:
- [x] after merge apply this to "all" left `regular meetup` issues

### CODE REVIEW

**Comment by h4cc** [comment]
When we have done some different Formats, these could be listed somewhere as well.

**Comment by OleMchls** [comment]
Yeah, I'd like to have a pool of activities we can choose from to set up a meet up. Still waiting for @LydG to upload our findings from the first meet up :wink:

**Comment by LydG** [comment]
Something like [this](ideas-for-topics.md)?

**Comment by OleMchls** [comment]
Yeah, exactly :D Somehow the link you posted seems broken so for further reference: https://github.com/hh-ex/planning/blob/master/ideas-for-topics.md

@h4cc what'd do you think about this list / pool of ideas?

**Pull request merged**
