### PR TITLE
Added "Goodies" to plan.

### PR DESCRIPTION
**Pull request by h4cc**
Hope i dont forget them next time :)

Erlang Solutions was quite generous with sponsoring a few goodies like stickers, pens and papers.

### CODE REVIEW

**Comment by OleMchls** [comment]
I wonder how this is a task for every meet up. Do you mean like, packing them? Or requesting them?

**Comment by h4cc** [comment]
If there are goodies from sponsors or such, they should be brought to the meetup. More like a reminder for this possibility.

**Comment by OleMchls** [comment]
While I see your point I find it hard to check the point while planning :)

**Comment by OleMchls** [comment]
Closing as stale. Feel free to add to the templates.

**Pull request closed without merging**
